### ISSUE TITLE
Units in Verification

### ISSUE THREAD

**Issue by martinferianc** [MatchLab-Imperial/keras_triplet_descriptor#2]
Hi, 

what are the units in the verification step, please? 

E.g.:

```
>> Running HPatch evaluation for custom
>> Please wait, loading the descriptor files...
>> Descriptor files loaded.
>> Evaluating verification task
Processing verification task 1/3 : 100% 1000000/1000000 [01:29<00:00, 11152.96it/s]
Processing verification task 2/3 : 100% 1000000/1000000 [01:30<00:00, 11071.81it/s]
Processing verification task 3/3 : 100% 1000000/1000000 [01:31<00:00, 10930.76it/s]
>> Verification task finished in 280 secs  
Verification task results:
CUSTOM - Balanced variant (auc) 
Noise       Inter     Intra
-------  --------  --------
Easy     0.919498  0.887013
Hard     0.899671  0.8601
Tough    0.871768  0.825558
CUSTOM - Imbalanced variant (ap) 
Noise       Inter     Intra
-------  --------  --------
Easy     0.806251  0.721069
Hard     0.738682  0.627186
Tough    0.657986  0.536444
```

**Comment by alopezgit** [comment]
I will update the repo with explanation of the evaluation protocol followed soon. The results are the Area Under the Curve (AUC) of the [ROC curve](https://en.wikipedia.org/wiki/Receiver_operating_characteristic) for the balanced case and mean Average Precision ([Precision-Recall explanation](https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html)) for the other case. It is explained in the [HPatches paper](https://arxiv.org/pdf/1704.05939.pdf) along with the tasks,

**Comment by martinferianc** [comment]
Got it, thanks!
