### ISSUE TITLE
Input Shape

### ISSUE THREAD

**Issue by martinferianc** [MatchLab-Imperial/keras_triplet_descriptor#3]
Hi,

why is the shape defined as `(32,32,1)`, when in the repo it says that the patches are actually `(64,64,1)`? Thanks for clarification.

**Comment by alopezgit** [comment]
We resized the original patches to (32, 32, 1) to reduce the size of the dataset and make it faster to both download and train.

**Comment by martinferianc** [comment]
Good choice :) Thanks!
